name        : gimp
version     : 2.8.16
release     : 14
source     :
    - http://download.gimp.org/pub/gimp/v2.8/gimp-2.8.16.tar.bz2 : 95e3857bd0b5162cf8d1eda8c78b741eef968c3e3ac6c1195aaac2a4e2574fb7
license     :
    - GPL-3.0
component   : multimedia.graphics
summary     : GNU Image Manipulation Program
description : |
    GIMP is a mature image editor with many advanced features and plugin support.
builddeps   :
    - pkgconfig(babl)
    - pkgconfig(gegl-0.2)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(atk)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - pkgconfig(cairo)
    - pkgconfig(gexiv2)
    - pkgconfig(libtiff-4)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(poppler-cairo)
    - pkgconfig(lcms2)
    - pkgconfig(xcursor)
    - pkgconfig(xpm)
    - pkgconfig(xfixes)
    - pkgconfig(xext)
    - pkgconfig(xmu)
    - pkgconfig(gudev-1.0)
    - libjpeg-turbo-devel
    - ghostscript-devel
rundeps     :
    - python-gobject2
setup      : |
    %configure --disable-static \
               --enable-shared \
               --with-cairo-pdf \
               --enable-sse \
               --enable-mmx \
               --enable-mp \
               --enable-default-binary
build      : |
    %make
install    : |
    %make_install
