name       : gimp
version    : 2.10.2
release    : 33
source     :
    - https://download.gimp.org/pub/gimp/v2.10/gimp-2.10.2.tar.bz2 : 1cb0baaecdefe44d371a15f2739a1bcbce4682336b4ccf8eb7b587ce52c333eb
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : GNU Image Manipulation Program
description: |
    GIMP is a mature image editor with many advanced features and plugin support.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(babl)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gexiv2)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jasper)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libexif)
    - pkgconfig(libmypaint)
    - pkgconfig(libopenjp2)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(mypaint-brushes-1.0)
    - pkgconfig(OpenEXR)
    - pkgconfig(poppler)
    - pkgconfig(pycairo)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(xmu)
    - pkgconfig(xpm)
    - aalib-devel
    - bzip2-devel
    - ghostscript-devel
    - poppler-utils
rundeps    :
    - mypaint-brushes
    - python-gobject2
    - python-gtk2
setup      : |
    %configure --with-bug-report-url=https://dev.solus-project.com/
build      : |
    %make
install    : |
    %make_install
