name       : gimp
version    : 2.10.0
release    : 31
source     :
    - https://download.gimp.org/pub/gimp/v2.10/gimp-2.10.0.tar.bz2 : 7fcc96fb88cb0a0595d2610f63a15dec245bb37bf9db527d37a24fb75e547de2
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : GNU Image Manipulation Program
description: |
    GIMP is a mature image editor with many advanced features and plugin support.
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(babl)
    - pkgconfig(cairo)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gegl-0.4)
    - pkgconfig(gexiv2)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(jasper)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libexif)
    - pkgconfig(libmypaint-gegl)
    - pkgconfig(libopenjp2)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(mypaint-brushes-1.0)
    - pkgconfig(poppler)
    - pkgconfig(pycairo)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xmu)
    - pkgconfig(xpm)
    - aalib-devel
    - bzip2-devel
    - ghostscript-devel
    - poppler-utils
rundeps    :
    - mypaint-brushes
    - python-gobject2
    - python-gtk2
setup      : |
    %configure --disable-static \
               --enable-shared \
               --with-cairo-pdf \
               --enable-sse \
               --enable-mmx \
               --enable-mp \
               --enable-default-binary
build      : |
    %make
install    : |
    %make_install
