name       : gimp
version    : 2.8.22
release    : 30
source     :
    - https://download.gimp.org/pub/gimp/v2.8/gimp-2.8.22.tar.bz2 : 9187a35cc52b110d78124d7b27b68a68ade14a794c2721314bac6134d2a5638a
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : GNU Image Manipulation Program
description: |
    GIMP is a mature image editor with many advanced features and plugin support.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(babl)
    - pkgconfig(cairo)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gegl-0.2)
    - pkgconfig(gexiv2)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libexif)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-cairo)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xmu)
    - pkgconfig(xpm)
    - aalib-devel
    - bzip2-devel
    - ghostscript-devel
    - jasper-devel
    - libjpeg-turbo-devel
rundeps    :
    - python-gobject2
    - python-gtk2
setup      : |
    %apply_patches
    %configure --disable-static \
               --enable-shared \
               --with-cairo-pdf \
               --enable-sse \
               --enable-mmx \
               --enable-mp \
               --enable-default-binary
build      : |
    %make
install    : |
    %make_install
