name       : gimp
version    : 2.8.20
release    : 21
source     :
    - http://download.gimp.org/pub/gimp/v2.8/gimp-2.8.20.tar.bz2 : 939ca1df70be865c672ffd654f4e20f188121d01601c5c90237214101533c805
license    :
    - GPL-3.0
component  : multimedia.graphics
summary    : GNU Image Manipulation Program
description: |
    GIMP is a mature image editor with many advanced features and plugin support.
builddeps  :
    - aalib-devel
    - ghostscript-devel
    - jasper-devel
    - libjpeg-turbo-devel
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(babl)
    - pkgconfig(cairo)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gegl-0.2)
    - pkgconfig(gexiv2)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libexif)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-cairo)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xmu)
    - pkgconfig(xpm)
rundeps    :
    - python-gobject2
setup      : |
    %configure --disable-static \
               --enable-shared \
               --with-cairo-pdf \
               --enable-sse \
               --enable-mmx \
               --enable-mp \
               --enable-default-binary
build      : |
    %make
install    : |
    %make_install
