name        : gimp
version     : 2.9.2
release     : 10
source     :
    - http://download.gimp.org/pub/gimp/v2.9/gimp-2.9.2.tar.bz2 : 85bed436b868b2e45ffab48d1bf5743006932770e8cca3322e345aefc000e29e
license     :
    - GPL-3.0
summary     : GNU Image Manipulation Program
builddeps   :
    - pkgconfig(babl)
    - pkgconfig(gegl-0.3)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(atk)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - pkgconfig(cairo)
    - pkgconfig(gexiv2)
    - pkgconfig(libtiff-4)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(poppler-cairo)
    - pkgconfig(lcms2)
    - pkgconfig(xcursor)
    - pkgconfig(xpm)
    - libjpeg-turbo-devel
    - ghostscript-devel
rundeps     :
    - python-gobject2
description : |
    GIMP is a mature image editor with many advanced features and plugin support.
setup      : |
    %configure --disable-static \
               --enable-shared \
               --with-cairo-pdf
build      : |
    %make
install    : |
    %make_install
